/**
 * @file
 * @author    block
 * @copyright (c) 2018 block.
 */

#ifndef PYRITE_CORE_NONCOPYABLE_HPP
#define PYRITE_CORE_NONCOPYABLE_HPP

namespace pyrite
{
namespace core
{
/**
 * class noncopyable cannot be copied.
 */
namespace noncopyable_ //!< protection from unintended ADL
{

class noncopyable
{
protected:
  /**
   * Default constructor.
   * generated by the compiler.
   */
  constexpr noncopyable() = default;

  /**
   * Destructor.
   * generated by the compiler.
   */
  ~noncopyable() = default;

  /**
   * Delete copy constructor.
   */
  noncopyable(noncopyable const&) = delete;

  /**
   * Delete copy assignment operator.
   */
  noncopyable& operator=(noncopyable const&) = delete;
}; // class noncopyable
} // namespace noncopyable_
} // namespace core

using noncopyable = pyrite::core::noncopyable_::noncopyable;
} // namespace pyrite

#endif // PYRITE_CORE_NONCOPYABLE_HPP
